// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4pLNwgf6eMADMV7aiv_s5-SHLR1XceiE',
    appId: '1:546255139861:web:cbf97c4e26025804afca1c',
    messagingSenderId: '546255139861',
    projectId: 'bjj-fitness-7b0c4',
    authDomain: 'bjj-fitness-7b0c4.firebaseapp.com',
    storageBucket: 'bjj-fitness-7b0c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1VlJ5HsKeZ1aeefpB2LXxo1sl0JYjrnM',
    appId: '1:546255139861:ios:9f293edd53de7ac1afca1c',
    messagingSenderId: '546255139861',
    projectId: 'bjj-fitness-7b0c4',
    storageBucket: 'bjj-fitness-7b0c4.firebasestorage.app',
    iosClientId: '546255139861-e9f4h0nmrib2c3ofu5ht72hlim9k6ddc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bjjApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4pLNwgf6eMADMV7aiv_s5-SHLR1XceiE',
    appId: '1:546255139861:web:a84cfcea7c847c82afca1c',
    messagingSenderId: '546255139861',
    projectId: 'bjj-fitness-7b0c4',
    authDomain: 'bjj-fitness-7b0c4.firebaseapp.com',
    storageBucket: 'bjj-fitness-7b0c4.firebasestorage.app',
  );
}
